name: SoBar
favicon: null
layout_spectrum: 0.682398569304496
typography_spectrum: 0.5453076621051878
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0070423283614218235
  lightness: 0.9784853807650506
  saturation: 0.08841785718686879
  rhythmicContrast: 0.29111259314231575
purpose: []
